// 150 коротких словосочетаний (3–4 слова) из имеющейся лексики — для вкладки
// «Предложения» и режима «Сопоставление». Фразы разделены пробелами по бунсэцу,
// чтобы чисто резались пополам. Засеиваются идемпотентно (см. db.js).

export const SEED_PHRASES = [
  // — еда, покупки, дом —
  { japanese: "お弁当を 作る", russian: "готовить бэнто" },
  { japanese: "お弁当を 食べる", russian: "есть бэнто" },
  { japanese: "野菜を 食べる", russian: "есть овощи" },
  { japanese: "野菜を 買う", russian: "покупать овощи" },
  { japanese: "畑で 野菜を 育てる", russian: "выращивать овощи на огороде" },
  { japanese: "店で 買い物する", russian: "делать покупки в магазине" },
  { japanese: "野菜が 甘い", russian: "овощи сладкие" },
  { japanese: "お弁当が おいしい", russian: "бэнто вкусный" },
  { japanese: "お弁当を 持つ", russian: "взять с собой бэнто" },
  { japanese: "お弁当を しまう", russian: "убрать бэнто" },

  // — учёба, школа —
  { japanese: "毎日 学校に 行く", russian: "каждый день ходить в школу" },
  { japanese: "電車で 学校へ 行く", russian: "ехать в школу на электричке" },
  { japanese: "学校に 着く", russian: "прибыть в школу" },
  { japanese: "学校で 勉強する", russian: "заниматься в школе" },
  { japanese: "図書館で 勉強する", russian: "заниматься в библиотеке" },
  { japanese: "毎日 勉強する", russian: "заниматься каждый день" },
  { japanese: "授業が 始まる", russian: "урок начинается" },
  { japanese: "授業が 終わる", russian: "урок заканчивается" },
  { japanese: "授業に 遅れる", russian: "опоздать на урок" },
  { japanese: "授業に 間に合う", russian: "успеть на урок" },
  { japanese: "授業が 面白い", russian: "урок интересный" },
  { japanese: "教室に 入る", russian: "входить в класс" },
  { japanese: "教室を 出る", russian: "выходить из класса" },
  { japanese: "制服を 着る", russian: "надевать форму" },
  { japanese: "学生に 教える", russian: "учить студентов" },

  // — вопросы, речь —
  { japanese: "先生に 質問する", russian: "задавать вопрос учителю" },
  { japanese: "先生に 聞く", russian: "спрашивать у учителя" },
  { japanese: "先生が 教える", russian: "учитель объясняет" },
  { japanese: "質問に 答える", russian: "отвечать на вопрос" },
  { japanese: "すぐに 答える", russian: "сразу ответить" },
  { japanese: "質問が 難しい", russian: "вопрос трудный" },
  { japanese: "質問が 簡単だ", russian: "вопрос простой" },
  { japanese: "言葉を 調べる", russian: "искать слово" },
  { japanese: "言葉が 分かる", russian: "понимать слова" },
  { japanese: "友達と 話す", russian: "разговаривать с другом" },
  { japanese: "先生と 話す", russian: "разговаривать с учителем" },

  // — друзья, встречи —
  { japanese: "友達に 会う", russian: "встречаться с другом" },
  { japanese: "友達と 遊ぶ", russian: "играть с другом" },
  { japanese: "友達を 待つ", russian: "ждать друга" },
  { japanese: "友達と 別れる", russian: "прощаться с другом" },
  { japanese: "友達が いる", russian: "есть друг" },
  { japanese: "久しぶりに 会う", russian: "встретиться впервые за долгое время" },
  { japanese: "来週 会う", russian: "встретиться на следующей неделе" },
  { japanese: "今日 友達に 会う", russian: "встретиться с другом сегодня" },
  { japanese: "先生を 待つ", russian: "ждать учителя" },
  { japanese: "少し 待つ", russian: "немного подождать" },

  // — досуг, прогулки —
  { japanese: "公園を 散歩する", russian: "гулять по парку" },
  { japanese: "公園で 遊ぶ", russian: "играть в парке" },
  { japanese: "友達と 散歩する", russian: "гулять с другом" },
  { japanese: "ゆっくり 散歩する", russian: "неспешно прогуляться" },
  { japanese: "音楽を 聞く", russian: "слушать музыку" },
  { japanese: "動画を 見る", russian: "смотреть видео" },
  { japanese: "動画を 作る", russian: "делать видео" },
  { japanese: "海で 泳ぐ", russian: "плавать в море" },
  { japanese: "川で 泳ぐ", russian: "плавать в реке" },
  { japanese: "山を 見る", russian: "смотреть на гору" },

  // — природа, погода —
  { japanese: "空が きれいだ", russian: "небо красивое" },
  { japanese: "星が きれいだ", russian: "звёзды красивые" },
  { japanese: "星が よく 見える", russian: "звёзды хорошо видны" },
  { japanese: "山が 見える", russian: "видна гора" },
  { japanese: "海が 近い", russian: "море близко" },
  { japanese: "天気が いい", russian: "погода хорошая" },
  { japanese: "天気が 悪い", russian: "погода плохая" },
  { japanese: "雨が 降る", russian: "идёт дождь" },
  { japanese: "雨が やっと 止む", russian: "дождь наконец прекращается" },
  { japanese: "風が 冷たい", russian: "ветер холодный" },
  { japanese: "風が 気持ちいい", russian: "ветер приятный" },
  { japanese: "とても 涼しい", russian: "очень прохладно" },
  { japanese: "今日は 暑い", russian: "сегодня жарко" },
  { japanese: "今日は 寒い", russian: "сегодня холодно" },
  { japanese: "空気が 暖かい", russian: "воздух тёплый" },

  // — дом, комната, дела —
  { japanese: "家に 帰る", russian: "возвращаться домой" },
  { japanese: "家を 出る", russian: "выходить из дома" },
  { japanese: "歩いて 帰る", russian: "идти домой пешком" },
  { japanese: "電車で 帰る", russian: "ехать домой на электричке" },
  { japanese: "部屋を 片付ける", russian: "прибирать комнату" },
  { japanese: "部屋を 掃除する", russian: "убираться в комнате" },
  { japanese: "部屋に 入る", russian: "входить в комнату" },
  { japanese: "部屋が 静かだ", russian: "в комнате тихо" },
  { japanese: "洗濯を する", russian: "стирать" },
  { japanese: "顔を 洗う", russian: "умывать лицо" },
  { japanese: "母を 手伝う", russian: "помогать маме" },
  { japanese: "家で 休む", russian: "отдыхать дома" },
  { japanese: "家で 過ごす", russian: "проводить время дома" },
  { japanese: "友達と 過ごす", russian: "проводить время с другом" },
  { japanese: "楽しく 過ごす", russian: "весело проводить время" },

  // — утро, сон, время —
  { japanese: "今朝 早く 起きる", russian: "встать рано сегодня утром" },
  { japanese: "すぐに 起きる", russian: "сразу встать" },
  { japanese: "もう 寝る", russian: "уже ложиться спать" },
  { japanese: "少し 寝る", russian: "немного поспать" },
  { japanese: "目が 覚める", russian: "просыпаться" },
  { japanese: "目を 覚ます", russian: "прогонять сон" },
  { japanese: "目覚まし時計が 鳴る", russian: "будильник звонит" },
  { japanese: "時計を 見る", russian: "смотреть на часы" },
  { japanese: "ゆっくり 休む", russian: "спокойно отдыхать" },
  { japanese: "昼休みに 休む", russian: "отдыхать в обеденный перерыв" },
  { japanese: "少し 休む", russian: "немного отдохнуть" },

  // — дорога, транспорт —
  { japanese: "駅まで 歩く", russian: "идти пешком до станции" },
  { japanese: "駅で 待つ", russian: "ждать на станции" },
  { japanese: "駅に 着く", russian: "прибыть на станцию" },
  { japanese: "電車を 待つ", russian: "ждать электричку" },
  { japanese: "電車に 遅れる", russian: "опоздать на электричку" },
  { japanese: "電車に 間に合う", russian: "успеть на электричку" },
  { japanese: "急いで 出かける", russian: "спешно выходить из дома" },
  { japanese: "道を 歩く", russian: "идти по дороге" },
  { japanese: "道が 分かる", russian: "знать дорогу" },
  { japanese: "道を 聞く", russian: "спрашивать дорогу" },
  { japanese: "走って 行く", russian: "бежать (туда)" },
  { japanese: "ゆっくり 歩く", russian: "медленно идти" },

  // — по пути, магазины —
  { japanese: "喫茶店に 寄る", russian: "заходить в кафе" },
  { japanese: "本屋に 寄る", russian: "заходить в книжный" },
  { japanese: "喫茶店で 話す", russian: "разговаривать в кафе" },
  { japanese: "喫茶店で 休む", russian: "отдохнуть в кафе" },
  { japanese: "店を 開ける", russian: "открывать магазин" },
  { japanese: "店を 閉める", russian: "закрывать магазин" },
  { japanese: "有名な 店", russian: "известный магазин" },

  // — вещи, находки —
  { japanese: "財布を 忘れる", russian: "забыть кошелёк" },
  { japanese: "財布を 探す", russian: "искать кошелёк" },
  { japanese: "財布が 見つかる", russian: "кошелёк нашёлся" },
  { japanese: "財布を 見つける", russian: "найти кошелёк" },
  { japanese: "財布を 使う", russian: "пользоваться кошельком" },
  { japanese: "電車を 使う", russian: "пользоваться электричкой" },
  { japanese: "時計が 壊れる", russian: "часы сломались" },
  { japanese: "時計を 壊す", russian: "сломать часы" },
  { japanese: "星を 見つける", russian: "заметить звезду" },
  { japanese: "虫を 捕まえる", russian: "ловить насекомое" },
  { japanese: "虫が いる", russian: "есть насекомое" },

  // — каникулы, деревня —
  { japanese: "夏休みが 始まる", russian: "летние каникулы начинаются" },
  { japanese: "夏休みが 終わる", russian: "летние каникулы заканчиваются" },
  { japanese: "夏休みを 過ごす", russian: "провести летние каникулы" },
  { japanese: "夏休みに 海へ 行く", russian: "поехать на море в летние каникулы" },
  { japanese: "田舎で 過ごす", russian: "проводить время в деревне" },
  { japanese: "田舎に 帰る", russian: "возвращаться в деревню" },
  { japanese: "田舎に 泊まる", russian: "ночевать в деревне" },
  { japanese: "友達の 家に 泊まる", russian: "ночевать у друга" },

  // — чувства, состояния —
  { japanese: "とても 嬉しい", russian: "очень рад" },
  { japanese: "少し 疲れた", russian: "немного устал" },
  { japanese: "とても 疲れた", russian: "очень устал" },
  { japanese: "気持ちが いい", russian: "приятно" },
  { japanese: "元気に なる", russian: "взбодриться" },
  { japanese: "とても 楽しい", russian: "очень весело" },
  { japanese: "笑って 喜ぶ", russian: "смеяться и радоваться" },
  { japanese: "困って 考える", russian: "растерянно раздумывать" },
  { japanese: "テストで 緊張する", russian: "нервничать на экзамене" },
  { japanese: "少し 緊張する", russian: "немного волноваться" },

  // — мысли —
  { japanese: "よく 考える", russian: "хорошо подумать" },
  { japanese: "少し 考える", russian: "немного подумать" },
  { japanese: "いいと 思う", russian: "думать, что хорошо" },
  { japanese: "面白いと 思う", russian: "думать, что интересно" },
  { japanese: "難しいと 思う", russian: "думать, что трудно" },
  { japanese: "忘れないと 思う", russian: "думаю, что не забуду" },
  { japanese: "思い出を 話す", russian: "рассказывать воспоминание" },

  // — предметы и признаки —
  { japanese: "新しい 制服", russian: "новая форма" },
  { japanese: "古い 時計", russian: "старые часы" },
  { japanese: "高い 財布", russian: "дорогой кошелёк" },
  { japanese: "大きい 家", russian: "большой дом" },
  { japanese: "小さい 虫", russian: "маленькое насекомое" },
  { japanese: "広い 公園", russian: "просторный парк" },
  { japanese: "静かな 部屋", russian: "тихая комната" },
  { japanese: "便利な 動画", russian: "полезное видео" },
  { japanese: "面白い 話", russian: "интересный рассказ" },
  { japanese: "懐かしい 思い出", russian: "ностальгическое воспоминание" },
  { japanese: "近い 駅", russian: "ближайшая станция" },
];
